### ISSUE TITLE
Replace README.pod with README.md

### ISSUE THREAD

**Issue by ufobat** [dagurval/perl6-image-resize#16]
I just want to suggest that you might want to remove the `README.pod` from the repo. Instead you could use `App::Mi6` in order to generate a `README.md` from the POD that is already in `lib/Image/Resize.pm`. In Addition mi6 takes care of your `META6.json` as well.

**Comment by dagurval** [comment]
Is this solved in #17?

**Comment by ufobat** [comment]
aye
